package models.utils

import java.awt.Image
import java.awt.image.BufferedImage
import java.io.ByteArrayInputStream
import java.util.*
import javax.imageio.ImageIO


data class PlaylistImage(var sourceStringBase64: String = "iVBORw0KGgoAAAANSUhEUgAAALoAAACKCAYAAAAddFBcAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFiUAABYlAUlSJPAAAAGKSURBVHhe7cgxEcAwAAOx8IeXtWBSAkbwp0GLzvnug7yZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZUDMTamZCzUyomQk1M6FmJtTMhJqZkHLfD6DM9VZqj1pRAAAAAElFTkSuQmCC")